# Env definition file for creating environment via conda

name: cmascience-env
channels:
 - conda-forge
dependencies:
 - python=3.7
 - iris=2.4
 - black
 - nccmp
 - libnetcdf
 - coverage
 - pytest
 - sphinx
 - sphinx_rtd_theme
 - cdsapi
 - holoviews
 - geoviews
 - xarray
 - jupyter
 - pip