# Content inspired from these sources
# https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml
# https://www.innoq.com/en/blog/github-actions-automation/
# https://github.com/marketplace/actions/publish-to-git
# https://github.com/seanmiddleditch/gha-publish-to-git/blob/master/entrypoint.sh
# https://github.com/JacksonMaxfield/github-pages-deploy-action-python/blob/master/entrypoint.sh


name: gh-pages

# Ensure pages only re-built after pushes to master branch not feature branches
on:
  push:
    branches:    
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      #with:
        #repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f bin/environment.yml
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        python setup.py install
    - name: Build and publish Sphinx documentation
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        
        # Setup the username and email.
        git config user.name "$GITHUB_ACTOR"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config pull.rebase true   # rebase
       
        # 
        repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
                
        cd bin
        chmod +x build-sphinx-docs.sh
        # Build the html documentation with sphinx
        ./build-sphinx-docs.sh
        
        echo $PWD
        echo "Documentation built"
        cd  ..
        echo $PWD
        cd docs/build
        echo $PWD
        git status
        echo "testing"
        echo $PWD
        
        git checkout -f gh-docs-pages
        #git pull origin gh-docs-pages 
        
        git add -f _static
        git add -f *.html
        git add -f *.inv
        git add -f *.js

        git status
        echo "here >>>>"
        
        # git commit -m "Update documentation" -a || true
        git commit -m "Update documentation on gh-docs-pages"
        echo "Push changes to gh-docs-pages branch"
        git remote set-url origin "$repo_uri" # includes access token
        
        git push --force-with-lease origin gh-docs-pages

        #cd ../..
        #echo $PWD
        #git subtree push --prefix docs/build origin gh-docs

      env:
        REMOTE_TESTS: True
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
