name: gh-pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f bin/environment.yml
        # conda create --name cma-env --file bin/environment_conda_spec_file.txt
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cma-env
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cma-env
        python setup.py install
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cma-env
        cd bin
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh
      env:
        REMOTE_TESTS: True
