name: gh-pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f bin/environment.yml
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        python setup.py install
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh
      env:
        REMOTE_TESTS: True
