# testing
# this main workflows runs over every push or pull request to master

  

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    # from https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch


    # invoke a repository_dispatch webhook event by calling the 
    # "Create a repository dispatch event" REST API endpoint. 
    # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
    - name: Create a workflow dispatches event
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -u ${{ secrets.ACCESS_TOKEN }} \
        https://api.github.com/repos/cma-open/cmascience/actions/workflows/after.yml/dispatches \
        -d '{"ref": "${{ steps.extract_branch.outputs.branch }}" }'
        # -d '{"ref":"master"}' 
     
# check re defien branch
# https://github.com/benc-uk/workflow-dispatch
#   ${{ github.event.pull_request.head.ref    
     
     
    - name: Create a repo level dispatches event
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -u ${{ secrets.ACCESS_TOKEN }} \
        https://api.github.com/repos/cma-open/cmascience/dispatches \
        -d '{"event_type":"trigger-this"}' 
 
 #curl \
 # -X POST \
 # -H "Accept: application/vnd.github.v3+json" \
 # https://api.github.com/repos/octocat/hello-world/actions/workflows/42/dispatches \
 # -d '{"ref":"ref"}'       
   
# curl \
# -u lightyears1998:$MY_GITHUB_PERSONAL_ACCESS_TOEKN_WITH_REPO_SCOPE 
# -H "Content-Type:application/json" 
# -X POST 
# -d '{"event_type": "fire-missile"}' 
# https://api.github.com/repos/lightyears1998/test-github-actions-event-target/dispatches   
