name: cmascience

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f bin/environment.yml
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        python setup.py install
    - name: Lint with flake8
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with coverage
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x test-coverage-remote.sh
        ./test-coverage-remote.sh
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh
      env:
        REMOTE_TESTS: True
