# resources from
# https://github.com/marketplace/actions/setup-miniconda
# https://github.com/marketplace/actions/setup-miniconda
# 
# https://github.com/actions/starter-workflows/issues/44

name: cmascience

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master branch 
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('bin/environment.yml') }}
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        channel-priority: strict
        environment-file: bin/environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!  

    - name: build-conda  
      #if: steps.cache-conda.outputs.cache-hit != 'true'
      run: |
        conda update conda
        conda config --show
        # added force flag to prevent errors when env already exists 
        conda env create -f bin/environment.yml --force
        conda config --show
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        python setup.py install
    - name: Lint with flake8
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with coverage
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x test-coverage-remote.sh
        ./test-coverage-remote.sh
    - name: Test Sphinx docs build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x build-sphinx-docs.sh
        ./build-sphinx-docs.sh
      env:
        REMOTE_TESTS: True
