# example schedule release

name: Scheduled monthly deploy release

on:
  #push:
    #branches:
    #  - master
  schedule:
    - cron: "*/5 * * * *" # Every 10 mins
    #- cron: '24 */24 * * *'  # Once a day
    #- cron: # Once per month
    #- cron: # Once per quarter

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
        #with:
        #repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a repo level release event
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -u ${{ secrets.ACCESS_TOKEN }} \
        https://api.github.com/repos/cma-open/cmascience/releases/new?tag=vTEST.0.0.1
        #https://api.github.com/repos/cma-open/cmascience/dispatches \
        #-d '{"event_type":"trigger-other"}'

          #https://github.com/octo-org/octo-repo/releases/new?tag=v1.0.1
          #https://github.com/octo-org/octo-repo/releases/new?tag=v1.0.1

