# example schedul release

name: Scheduled monthly deploy release

#On:
  push:
    branches:
      - master
  schedule:
    - cron: '24 */24 * * *'  # Once a day
    - cron: # Once per month
    - cron: # Once per quarter

jobs:
  deploy:
    runs-on: ubuntu-18.04
