# example schedule release
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-release
# using calver https://calver.org/calendar_versioning.html
# calver YYYY.0M.0D.MICRO
# using semver https://semver.org/
# semver MAJOR.MINOR.PATCH.pre-release

name: Scheduled  automated release

on:
  push:
    
  schedule:
    - cron: "* * * * *" # Run every minute, e.g. for testing only
    #- cron: "0 * * * *" # Every hour
    #- cron: '0 0 * * *' # Once a day
    #- cron: '0 0 1 * *' # Once per month
    #- cron: '0 0 1 */2 *' # Every other month (1st day of month)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d.T%Hh%Mm')"
      #run: echo "::set-output name=date::$(date +'%Y.%m.%d.Dev')"
 #   - name: Get release notes
 #     id: notes
 #     run: echo "::set-output name=body::'Release notes text here'"
    - name: Get release
      id: release
      run: echo ::set-output name=release::$(cat RELEASE)
    - name: Get version
      id: vars
      run: echo ::set-output name=version::$(cat VERSION)
    - name: Test output
      run: | 
        echo ${{ steps.vars.outputs.version }}
        echo ${{ steps.release.outputs.release }}
        echo ${{ steps.date.outputs.date }}
    - name: Create a repo level release event
      env:
        TAG: '"tag_name":"v${{ steps.vars.outputs.version }}"'
        TAG2: "'tag_name':'v${{ steps.vars.outputs.version }}'"
        RELEASE: '"prerelease": true'
        BODY: '"body":"${{ steps.release.outputs.release }}"'
        #DATA: "tag_name":"v${{ steps.vars.outputs.version }}.rc-${{ steps.date.outputs.date }}", "prerelease": true, "body":"${{ steps.release.outputs.release }}"      
      run: | 
        echo "$TAG"
        echo "$TAG""
        echo ""$TAG","$RELEASE""
        echo "$TAG","$RELEASE"
 
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -u ${{ secrets.ACCESS_TOKEN }} \
        https://api.github.com/repos/cma-open/cmascience/releases \
        #-d '{$TAG}'
        -d '{"$TAG2"}'
        
        #-d '{"name":"test_name"}'

       

