# resources from
# https://github.com/asarkar/build-time-tracker/blob/master/.github/workflows/publish.yml

name: unit-tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master branch 
      uses: actions/checkout@v2
    - name: Check CI status
      run: >
        output=$(curl -sSL -X GET -G -H 
        "Accept: application/vnd.github.v3+json" 
        -d "branch=${{ env.GITHUB_REF_SLUG }}" 
        -d "event=push" 
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.event.inputs.ci }}/runs | jq -r '.workflow_runs[0] | "\(.conclusion)"')
        echo "::set-output name=status::$output"
      id: check

    - name: Abort if CI not successful
      if: steps.check.outputs.status != 'success'
      run: |
        echo ${{ steps.check.outputs.status }}
        exit 1   
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('bin/environment.yml') }}
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        channel-priority: strict
        environment-file: bin/environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!  
    
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmascience
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        python setup.py install
    - name: Test with coverage
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate cmascience-env
        cd bin
        chmod +x test-coverage-remote.sh
        ./test-coverage-remote.sh
